### ISSUE TITLE
Два контроллера

### ISSUE THREAD

**Issue by Enzokot** [allovaro/neptun_homeassistant#4]
Добрый день.
Огромное спасибо за интеграцию, которая позволяет избежать зависимость от облака!
В документации не нашел, возможно ли подключить два контроллера?

**Comment by bisquit2003** [comment]
> Добрый день. Огромное спасибо за интеграцию, которая позволяет избежать зависимость от облака! В документации не нашел, возможно ли подключить два контроллера?

здравствуйте, а у вас работает нормально? у меня модуль prow+wifi постоянно отваливается от сети, уже и по гарантии его менял. пришлось использовать облачную интеграцию

**Comment by Enzokot** [comment]
@bisquit2003 работает, но у меня АР не далеко от контроллера. А в целом да, вифи там не лучший модуль

**Comment by bisquit2003** [comment]
> @bisquit2003 работает, но у меня АР не далеко от контроллера. А в целом да, вифи там не лучший модуль

ну чет хз, и роутер и сст клауд показывает хороший линк, ставил для него лично в ванной роутер - ниче не поменялось

**Comment by allovaro** [comment]
> 

Добрый день, не проверял. Но по идее не должно быть проблем с этим

**Comment by allovaro** [comment]
> Добрый день. Огромное спасибо за интеграцию, которая позволяет избежать зависимость от облака! В документации не нашел, возможно ли подключить два контроллера?

Добрый день, не проверял. Но по идее не должно быть проблем с этим

**Comment by Enzokot** [comment]
@allovaro подскажите, пожалуйста, как в такой ситуации настроить конфигурацию платформы?

**Comment by SerjD1t** [comment]
Приветствую, со SMART+ не работает?
