### ISSUE TITLE
Инструкция

### ISSUE THREAD

**Issue by sabir81106** [allovaro/neptun_homeassistant#6]
Здравствуйте! Новичок в Home Assistant.

Подскажите, в инструкции написано скопировать папку custom_integration, но ее нет  в проекте.
Все обьекты добавлять в configuration.yaml?

**Comment by allovaro** [comment]
Здравствуйте, там имеется в виду, что эту интеграцию нужно скопировать в папку custom_components. В самом репозитории специально так и создан путь ./custom_components/neptun. По умолчанию папки custom_components у вас не будет. Ее нужно создать в корне HA.

**Comment by sabir81106** [comment]
Спасибо!
